package parser;

public enum Code {
    A_EQUAL_10, SIMPLE_ADD_CLOSURE, SIMPLE_SUBTRACT_CLOSURE,
    SIMPLE_MULTIPLICATION_CLOSURE, CONSEC_MULTIPLICATION_CLOSURE, NESTED_CLOSURE,
    COUNTER_MAKER_CLOUSURE, IF_CLOSURE, IF_ELSE_CLOSURE, MINOR, TEST_WHILE, TEST_PRINTP1P2, TEST_EMPTY_LAMBDA,
    SIMPLE_ADD_STRING_CLOSURE, TEST_MODULE;
}
