package parser;

public enum Code {
    A_EQUAL_10, SIMPLE_ADD_CLOSURE, SIMPLE_SUBTRACT_CLOSURE,
    SIMPLE_MULTIPLICATION_CLOSURE, CONSEC_MULTIPLICATION_CLOSURE, NESTED_CLOSURE,COUNTER_MAKER_CLOUSURE;
}
